default_language_version:
  python: python3.12
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: name-tests-test

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - -i
          - -r
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  #- repo: https://github.com/psf/black
  #  rev: 24.3.0
  #  hooks:
  #    - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-tidy-imports
        args: [--max-line-length=88, '--extend-ignore=E203,E501,E402,F403,F405']

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.9'
    hooks:
    - id: bandit
      args: ["-r", "."]


  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
