name: da-kit-project
networks:
  infra_network:
    driver: bridge

services:
  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - infra_network
